version: '3.8'

services:
  signaling-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MEDIASOUP_LISTEN_IP=0.0.0.0
      - MEDIASOUP_ANNOUNCED_IP=127.0.0.1
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  mediasoup-server:
    build:
      context: ./server
      dockerfile: Dockerfile.mediasoup
    ports:
      - "40000-40100:40000-40100/udp"
      - "40000-40100:40000-40100/tcp"
    environment:
      - NODE_ENV=development
      - MEDIASOUP_LISTEN_IP=0.0.0.0
      - MEDIASOUP_ANNOUNCED_IP=127.0.0.1
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run mediasoup 